language: cpp

env:
  global:
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps


matrix:
    include:
        os: linux
        dist: trusty
        sudo: true
        compiler: gcc
        addons:
        apt:
        packages: &precise_latest_boost_packages
            - gcc-4.8
            - g++-4.8
            #- gcov-4.9
            - clang-3.7
            - valgrind
            # Misc
            - python-yaml
            - lcov
            - libopencv-dev
        sources: &precise_latest_boost_sources
           - ubuntu-toolchain-r-test
           - llvm-toolchain-precise-3.7

install:
    - mkdir -p ${TRAVIS_BUILD_DIR}/DEPS
    #install cmake
    - mkdir -p ${TRAVIS_BUILD_DIR}/DEPS/cmake
    - travis_retry wget --no-check-certificate --quiet -O - http://www.cmake.org/files/v3.5/cmake-3.5.1-Linux-x86_64.tar.gz | tar --strip-components=1 -xz -C ${TRAVIS_BUILD_DIR}/DEPS/cmake
    - export PATH=${TRAVIS_BUILD_DIR}/DEPS/cmake/bin:${PATH}
    - echo ${PATH}
    #download gtest
    - cd ${TRAVIS_BUILD_DIR}/DEPS
    - wget  http://ftp.hu.debian.org/debian/pool/main/g/googletest/libgtest-dev_1.10.0-2_amd64.deb
    - wget  http://ftp.hr.debian.org/debian/pool/main/g/googletest/googletest_1.10.0-2_all.deb
    #dpkg update
    - sudo apt-get clean
    - sudo apt-get update
    - sudo apt-get install dpkg
    #opening
    - sudo dpkg -i googletest_1.10.0-2_all.deb
    - sudo dpkg -i libgtest-dev_1.10.0-2_amd64.deb
    - cd /usr/src/gtest
    - sudo env "PATH=$PATH" cmake CMakeLists.txt
    - sudo make
    - sudo cp *.a /usr/lib
branches:
    only:
        - temp_travis
script:
    - cd ${TRAVIS_BUILD_DIR}
    - cmake CMakeLists.txt
    - make
    - ./runTests
    
