language: cpp

env:
  global:
    - CXX_FLAGS="-std=c++11 -Wall -pedantic -Werror -Wno-variadic-macros -Wno-long-long -Wno-shadow"

dist: xenial
compiler: gcc
addons:
    apt:
        packages: &precise_latest_boost_packages
            - gcc-5
            - g++-5
            - cmake
        sources:  &precise_latest_boost_sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
               

branches:
    only:
        - temp_travis
script:
    - mkdir build && cd build 
    - cmake .. 
    - make all
    - ls
    - cd ..
    - ./runTests


