language: cpp

env:
  global:
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps


matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      compiler: gcc

before_install: 
    - mkdir -p ${DEPS_DIR}/gtest
    - cd ${DEPS_DIR}/gtest
    - wget  http://ftp.hu.debian.org/debian/pool/main/g/googletest/libgtest-dev_1.10.0-2_amd64.deb
    - wget  http://ftp.hr.debian.org/debian/pool/main/g/googletest/googletest_1.10.0-2_all.deb
    - sudo apt-get clean
    - sudo apt-get update
    - sudo apt-get install dpkg
    - sudo dpkg -i googletest_1.10.0-2_all.deb
    - sudo dpkg -i libgtest-dev_1.10.0-2_amd64.deb

branches:
    only:
        - temp_travis
script:
    - cd ${TRAVIS_BUILD_DIR}
    - ls
    - make
    - TEST
    
